### ISSUE TITLE
The query for the infercode datasets: 

### ISSUE THREAD

**Issue by mengyuan-Sharon** [bdqnghi/infercode#1]
Thanks for your wonderful work, your work gave me a lot of inspiration！May I ask you something about the dataset and dataset processing details that papers do? As you said, there is only part of the data in the current repo, to run through the infercode, there are still missing datasets in  "train_path", "train_label_path", "Val path", "val_label_path" and "subtree_vocabulary_path", etc. Would you please give us these data formats or a small number of samples at those files for us to run the infercode?  Another question is, how did you extract the subtree of an AST? Can the details of the extraction code be shown? 

Looking forward to your reply! 

Thanks a lot!  

Sincerely student.

**Comment by bdqnghi** [comment]
hi, thanks for reaching out. We haven't finished updating the repo. We will do it and update you asap.

**Comment by bdqnghi** [comment]
i have updated the code, you can try to follow the instruction again

**Comment by Avv22** [comment]
@bdqnghi. Thank you. So can we just predict embeddings for file inputs like pip infercode file.py without going with training model from scratch on a new Python dataset please?
