### ISSUE TITLE
'InferCodeClient' object has no attribute 'ast_parser'

### ISSUE THREAD

**Issue by sqhan-Husky** [bdqnghi/infercode#14]
l have tried 'InferCodeClient' successfully to generate vectors for c-language with your hints in the Readme file. However, when l want to change the language to java by 'InferCodeClient(language="java")', the encode function meet an error.

![image](https://user-images.githubusercontent.com/45597101/132855622-3d6a1072-4959-4678-8a08-7cd7b77f3aaa.png)

Can the Infercode as Pypi package support other languages except for c now?

**Comment by bdqnghi** [comment]
hi, i have just had a checked, the code is working normally, can you make sure that you are using the latest version (0.0.27)?

**Comment by sqhan-Husky** [comment]
Thanks for your reply.
I notice that the key is the line 'infercode.init_from_config()'. 
If l first run the function on c-language InferCodeClient in a jupyter notebook and then run a new-created java InferCodeClient, it get an unexpected problem.
![image](https://user-images.githubusercontent.com/45597101/132866177-c9430984-5573-4a0c-aa8d-a4730d79c7d6.png)
![image](https://user-images.githubusercontent.com/45597101/132866213-9df7c550-c1e7-4124-ba03-bd9343dfe656.png)
![image](https://user-images.githubusercontent.com/45597101/132866395-56de6968-efef-45b1-8624-96dcbd34dcbc.png)
So l just ignore this line and get the previous error.

If I run it in a new notebook, it can work normally.

**Comment by sqhan-Husky** [comment]
By the way, I'm interested in your project and the main paper and want to research your model in detail.
Is the source code in 'old_version' folder in accordance with your developed Pypi package?

**Comment by bdqnghi** [comment]
The "old_version" is obsolete, i'm not actively maintaining it anymore, the source code in "infercode" is the one in accordance with the Pypi.

**Comment by sqhan-Husky** [comment]
OK, I will try it. Thanks for sharing your code with the public!
