### ISSUE TITLE
Training the model

### ISSUE THREAD

**Issue by shaileshj2803** [bdqnghi/infercode#16]
Awesome work. I am trying to train the model on my own data.
Where is the model saved after fine tuning? i tried example from test script. Also for inference how can i load the saved model?
Thanks a lot

**Comment by shaileshj2803** [comment]
no longer needed

**Comment by Avv22** [comment]
@shaileshj2803. Hello!

I am having same trouble, I am trying to get their pretrained model, but it seems it's for Java and not for Python, should I train the model from scratch please?
