### ISSUE TITLE
the result is different with the page example

### ISSUE THREAD

**Issue by 850tomato** [bdqnghi/infercode#17]
Hi,
   Thanks for your work!
    I have a simple question, the test.py which I run is different with your readme example, That is OK?
  
![image](https://user-images.githubusercontent.com/36918334/139077824-72d52b30-dd59-4a94-b9f1-f5bc20dc30f0.png)
![image](https://user-images.githubusercontent.com/36918334/139077840-a174abe6-0859-440a-97bf-733773db01db.png)
    Thanks!

**Comment by yijunyu** [comment]
it is possible that our underlying pretraining model has been upgrade/updated. If you want to have exact results perhaps you will need to save the pretrained models of particular date/version, but generally our newly provided pretrained model would be better because it is built on more code ...

**Comment by 850tomato** [comment]
Thanks！

**Comment by 850tomato** [comment]
Another question. It just output a 1X50 numpy vector whether you put a small piece code segment or a function with large number of code line(small granualarity or big  granualarity).  Whether the output vector is too small and lack of enough information , if I want do some downstream tasks, such like code vulnerability detection. Thanks!
