### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/wy/.tree-sitter/tree-sitter-parsers-Linux'

### ISSUE THREAD

**Issue by tjuTangSong** [bdqnghi/infercode#19]
Hi! I'm running the test script given in Readme on ubuntu 18.04, my python version is 3.8.12, and I get the following error, how can I solve it? 
I download Linux.zip successfully.
Thanks!

**Comment by allomy** [comment]
Hi, I met the same one, could you give some informations about how do you solve this problem?


---------------------------------
[Update] The solution is as following:
```
cd /home/wy/.tree-sitter
unzip Linux.zip
```

**Comment by tjuTangSong** [comment]
> 
Hi, you can go to the "/.tree-sitter" directory and unzip "Linux.zip" manually, that solved my problem.

**Comment by allomy** [comment]
Thank you @tjuTangSong for your response.
