### ISSUE TITLE
Download the pretrained model to generate embeddings

### ISSUE THREAD

**Issue by Avv22** [bdqnghi/infercode#21]
Thank you InferCode team for this work.

Can you pleas provide a link to your pretrained model? Does this model works with any language please or we have to train it from scratch based on target language? Also, can we provide CSV file that contains one file that has program for each row please?

Regards,

**Comment by allomy** [comment]
Hi @Avra2 , I faced the similar issue that, so have you got the linkage about the pretrained model?
