### ISSUE TITLE
can not download dataset

### ISSUE THREAD

**Issue by iamfaith** [bdqnghi/infercode#33]
Thanks for your great work. But I got the following error while trying to download the dataset. Could you please send me the dataset? 

![image](https://user-images.githubusercontent.com/16201784/197142926-3a0ced86-8337-4bf5-b16d-39b7f82f7b2f.png)

**Comment by tianzhaotju** [comment]
: )  Hello, how do you solve this proble?  I aslo want to download the dataset? 
I would appreciate it very much if you would help me!
