### ISSUE TITLE
When run train.py, an error shows "AttributeError: 'Namespace' object has no attribute 'model_name'"

### ISSUE THREAD

**Issue by chontipan** [bdqnghi/infercode#5]
![image](https://user-images.githubusercontent.com/9138402/122392543-8a7e8400-cfa6-11eb-89e1-587ba4405111.png)

Hi authors, what model_name to be an input?

**Comment by bdqnghi** [comment]
can you try to run again? i have just update some fixings

**Comment by chontipan** [comment]
Thanks!
