### ISSUE TITLE
pip infercode无法使用

### ISSUE THREAD

**Issue by ju-king** [bdqnghi/infercode#6]
after pip infercode，how to use？

**Comment by yijunyu** [comment]
```base
pip install infercode
```

Then you need to run it using the example code:

```bash
cd tests
python test_infer.py
```

**Comment by Avv22** [comment]
@yijunyu. Thank you. Is your infercode internally has pretrained models for Python and Java as I see in your old version you have separate pretrained model on small java dataset please?

**Comment by yijunyu** [comment]
My understanding, the "universal" model has been trained on several languages, it should work for python / java as well. @bdqnghi.

**Comment by Avv22** [comment]
Yes! Thanks. Should we use paramster `language=python` for python for
example? What we tags we should use for languages? The only example
provided is for C on main repository.
