### ISSUE TITLE
AttributeError: 'InferCodeClient' object has no attribute 'ast_util'

### ISSUE THREAD

**Issue by ju-king** [bdqnghi/infercode#7]

**Comment by ju-king** [comment]
from infercode.client.infercode_client import InferCodeClient
infercode = InferCodeClient(language="c")
vectors = infercode.encode(["for (i = 0; i < n; i++)"])
print(vectors)
run this show AttributeError: 'InferCodeClient' object has no attribute 'ast_util'

**Comment by yijunyu** [comment]
The problem has been fixed.
